#!/bin/bash

# Step 1: Create warehouse, database, schema, and tables
snowsql -c default -q "
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE NATIVE_APP_QUICKSTART_WH WAREHOUSE_SIZE=SMALL INITIALLY_SUSPENDED=TRUE;
CREATE OR REPLACE DATABASE NATIVE_APP_QUICKSTART_DB;
USE DATABASE NATIVE_APP_QUICKSTART_DB;
CREATE OR REPLACE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;
USE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;

CREATE OR REPLACE TABLE MFG_SHIPPING (
  order_id NUMBER(38,0), 
  ship_order_id NUMBER(38,0),
  status VARCHAR(60),
  lat FLOAT,
  lon FLOAT,
  duration NUMBER(38,0)
);

CREATE OR REPLACE TABLE MFG_ORDERS (
  order_id NUMBER(38,0), 
  material_name VARCHAR(60),
  supplier_name VARCHAR(60),
  quantity NUMBER(38,0),
  cost FLOAT,
  process_supply_day NUMBER(38,0)
);

CREATE OR REPLACE TABLE MFG_SITE_RECOVERY (
  event_id NUMBER(38,0), 
  recovery_weeks NUMBER(38,0),
  lat FLOAT,
  lon FLOAT
);
"

# Step 2: Create Stages for Data Upload
snowsql -c default -q "
USE WAREHOUSE NATIVE_APP_QUICKSTART_WH;
USE DATABASE NATIVE_APP_QUICKSTART_DB;
USE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;

CREATE OR REPLACE STAGE MFG_SHIPPING FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER=1, FIELD_OPTIONALLY_ENCLOSED_BY='\"');
CREATE OR REPLACE STAGE MFG_ORDERS FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER=1, FIELD_OPTIONALLY_ENCLOSED_BY='\"');
CREATE OR REPLACE STAGE MFG_SITE_RECOVERY FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER=1, FIELD_OPTIONALLY_ENCLOSED_BY='\"');
"

# Step 3: Upload Data to Snowflake Stages
snowsql -c default -q "
USE WAREHOUSE NATIVE_APP_QUICKSTART_WH;
USE DATABASE NATIVE_APP_QUICKSTART_DB;
USE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;

PUT 'file://$(pwd)/app/data/shipping_data.csv' @MFG_SHIPPING AUTO_COMPRESS=FALSE;
PUT 'file://$(pwd)/app/data/order_data.csv' @MFG_ORDERS AUTO_COMPRESS=FALSE;
PUT 'file://$(pwd)/app/data/site_recovery_data.csv' @MFG_SITE_RECOVERY AUTO_COMPRESS=FALSE;
"

# Step 4: Copy Data from Stage to Tables
snowsql -c default -q "
USE WAREHOUSE NATIVE_APP_QUICKSTART_WH;
USE DATABASE NATIVE_APP_QUICKSTART_DB;
USE SCHEMA NATIVE_APP_QUICKSTART_SCHEMA;

COPY INTO MFG_SHIPPING FROM @MFG_SHIPPING FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY='\"');
COPY INTO MFG_ORDERS FROM @MFG_ORDERS FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY='\"');
COPY INTO MFG_SITE_RECOVERY FROM @MFG_SITE_RECOVERY FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY='\"');
"

echo "✅ Deployment completed successfully!"
